services:
  app:
    build:
      # ビルドを実行する際の基準となるフォルダ
      context: .
      # 実際に使用するDockerfileの場所
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - mysql
    volumes:
      # ローカルのPHP設定ファイルをコンテナ内のPHP設定ファイルにマウントする
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
      # ローカルのFuelPHPアプリケーションをコンテナ内にマウントする
      - ./app:/var/www
    # コンテナ内での作業ディレクトリを指定する
    working_dir: /var/www
    # localの8080ポートをコンテナの8080ポートにマッピングする
    ports:
      - "8080:8080"
    # コンテナ起動時に実行するコマンドを指定する（PHPの組み込みWebサーバーを起動する）
    command: "php -S 0.0.0.0:8080 -t public"

  mysql:
    image: mysql:5.6
    platform: linux/amd64
    # 1回のリクエストで受け取れるデータのサイズを上げておく
    command: --max_allowed_packet=32505856
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fuel
    ports:
      - 3306:3306